server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml
    drop-first: false

  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /docs

jwt:
  secret-key: ${JWT_SECRET}
  expiration: 360000000

aes:
  secret-key: ${AES_SECRET}

security:
  unauthenticated-endpoints:
    - /api/auth/login
    - /api/auth/register

app:
  cards:
    validity-period-days: 1825 # 5 years
    validity-check-cron: "0 0 0 * * *"
  currencies:
    default: RUB
    rates:
      USD:
        RUB: 90.50
        EUR: 0.92
      EUR:
        RUB: 98.20
        USD: 1.09
      RUB:
        USD: 0.011
        EUR: 0.010