server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml
    drop-first: false

  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  group-configs:
    - group: everything
      paths-to-match: /api/**
      display-name: All API

    - group: admin
      paths-to-match: /api/admin/**
      display-name: Admin API

    - group: user
      paths-to-match: /api/**
      paths-to-exclude: /api/admin/**
      display-name: User API

    - group: unauthenticated user
      paths-to-match: /api/auth/**
      display-name: Unauthenticated User API

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.bankcards: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB


jwt:
  secret-key: ${JWT_SECRET}
  expiration: 360000000

aes:
  secret-key: ${AES_SECRET}

security:
  unauthenticated-endpoints:
    - /api/auth/login
    - /api/auth/register
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/**

app:
  cards:
    validity-period-days: 1825 # 5 years
    validity-check-cron: "0 0 0 * * *"
  currencies:
    rates:
      USD:
        RUB: 90.50
        EUR: 0.92
      EUR:
        RUB: 98.20
        USD: 1.09
      RUB:
        USD: 0.011
        EUR: 0.010